spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.118.105:3306/ljs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ljs
    password: 123456
    druid:
      initial-size: 5  # 初始连接数
      min-idle: 5      # 最小空闲连接数
      max-active: 20   # 最大连接数
      max-wait: 60000  # 获取连接等待超时时间
      time-between-eviction-runs-millis: 60000  # 检测连接是否有效的周期
      min-evictable-idle-time-millis: 300000    # 连接在池中最小生存时间
      validation-query: SELECT 1               # 验证连接有效性的 SQL 查询
      test-while-idle: true                    # 申请连接前验证连接有效性
      test-on-borrow: false                    # 申请连接时验证连接有效性
      test-on-return: false                    # 归还连接时验证连接有效性
  redis:
    host: 116.62.118.105
    port: 6379

server:
  port: 8080